### ISSUE TITLE
Function Declarations are set the first time a function is called and do not change on subsequent calls.

### ISSUE THREAD

**Issue by davidcourtney** [kevinbirch/Djinn#7]
# Setup

In the following example I define a function dipinc that adds one to the second item in the stack.

[dipinc drop 1 add top' \top' [id]]
## Expected

User> **10 20 dipinc**
stack: 11 20

User> **30 40 dipinc**
stack: 11 20 31 40
## Actual Result

User> **10 20 dipinc**
stack: 11 20

User> **30 40 dipinc**
stack: 11 20 31 20

The value of top' appears to be set to 20 on the first call and does not change on subsequent calls.

**Comment by kevinbirch** [comment]
Yeah, I actually had a todo item about this.  This is caused by the implementation of declarations, they cache their results so they can be executed multiple times within a function.  I think the Declaration interface needs a method like initialize() that will set up the cache, and then execute would just return it.  Then, in the execute() method of ModuleFunction, it would call that new method instead of execute().  The execute() method would be called later when the word for that declaration was evaluated.

Would you like to fix it?

**Comment by davidcourtney** [comment]
Potential fix for this is in commit 93550f2f
